name: backend
services:
  backend_server:
    build: .
    image: zackjmccann/backend-server-dev:0.0.1-dev
    # image: us-east1-docker.pkg.dev/spotted-apple/backend/client-test:0.0.1-dev
    container_name: backend-server-dev
    env_file:
      - '.env'
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    ports:
      - "8000:8000"

  local_pg:
    image: postgres:16.6-bullseye
    container_name: local-pg
    env_file:
      - '.env'
    volumes:
      - local_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  local_pg_data: