name: backend_${PRIMARY_CONTAINER}
services:
  aloe:
    build: 
      dockerfile: ../Dockerfile
    image: ${PRIMARY_IMAGE}
    container_name: ${PRIMARY_CONTAINER}
    networks:
      db_network:
        aliases:
          - db_net
    env_file:
      - "../.env"
    restart: "${DOCKER_RESTART_POLICY:-no}"
    volumes:
    - ./pgdata:/data
    - ./config:/config
    - ./archive:/mnt/server/archive

networks:
  db_network:
    name: db_network
